apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: php
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: lona269/php-app:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "ashiqdb.c3w8ms64o98h.us-east-1.rds.amazonaws.com"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        - name: DB_NAME
          value: "ashiqdb"

